-- AlterTable
ALTER TABLE `order` ADD COLUMN `isDone` BOOLEAN NULL;

-- AlterTable
ALTER TABLE `orderstatus` MODIFY `status` ENUM('AWAITING_DRIVER_PICKUP', 'DRIVER_TO_OUTLET', 'DRIVER_ARRIVED_AT_OUTLET', 'AWAITING_PAYMENT', 'IN_WASHING_PROCESS', 'IN_IRONING_PROCESS', 'IN_PACKING_PROCESS', 'PAYMENT_DONE', 'DRIVER_TO_CUSTOMER', 'DRIVER_DELIVERED_LAUNDRY') NOT NULL;
