export enum Role {
    SUPER_ADMIN = 'SUPER_ADMIN',
    OUTLET_ADMIN = 'OUTLET_ADMIN',
    WASHING_WORKER = 'WASHING_WORKER',
    IRONING_WORKER = 'IRONING_WORKER',
    PACKING_WORKER = 'PACKING_WORKER',
    DRIVER = 'DRIVER',
}